openapi: 3.2.0
info:
  title: Data Use Governance - Data Catalog Catalog Search V1 API
  description: The Data Catalog APIs provide comprehensive functionality for managing data governance assets within Data Catalog, enabling users to create, retrieve, and organize business glossaries, terms, and tags for effective data classification and metadata management.
  version: '1.0'
  contact:
    name: OneTrust Support
    url: https://my.onetrust.com/s/contactsupport
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
- url: https://{hostname}
  variables:
    hostname:
      default: hostname
      description: The OneTrust hostname such as app.onetrust.com, app-eu.onetrust.com, app-de.onetrust.com, app-uk.onetrust.com, app-apac.onetrust.com, trial.onetrust.com, or uat.onetrust.com.
tags:
- name: Catalog Search V1
  description: APIs to manage catalog search operations with basic functionality and providing comprehensive filtering, faceting, and field selection capabilities for data asset discovery.
  externalDocs:
    description: OpenAPI 3.1.0 - Download Definition
    url: https://developer.onetrust.com/onetrust/openapi/data-use-governance-data-catalog.json
  x-displayName: Catalog Search V1
paths:
  /api/data-governance/v1/catalog/search:
    post:
      operationId: externalSearch
      summary: Get Catalog Search Results
      description: 'Use this API to retrieve a list of all catalog search results by key terms and filters. The response will include relevant details for each result, including the corresponding data asset ID, name, and the associated tags and terms.


        > 🗒 Things to Know

        >

        > - This API returns up to 100,000 catalog search results. For larger volumes, use the Get Catalog Search Results V2 API.'
      tags:
      - Catalog Search V1
      x-onetrust:
        spec-label: https://developer.onetrust.com/onetrust/openapi/data-use-governance-data-catalog.json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_SearchRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_SearchResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '429':
          description: "Too Many Requests. \nFor more information, see [API Rate Limits](https://developer.onetrust.com/onetrust/reference/rate-limits-overview)."
          headers:
            Retry-After:
              schema:
                description: The number of seconds after which requests will be allowed again.
                format: int32
            ot-period:
              schema:
                description: The unit of time for which the rate limit applies
                enum:
                - HOUR
                - MINUTE
            ot-ratelimit-event-id:
              schema:
                description: The unique identifier for the rate-limiting event.
                format: uuid
            ot-request-made:
              schema:
                description: The number of requests made within the specified period.
                format: int32
            ot-requests-allowed:
              schema:
                description: The number of requests allowed within the specified period.
                format: int32
        '500':
          description: Internal Server Error
      security:
      - DataUseGovernance-DataCatalogMetadataExchange_OAUTH2:
        - DATA_CATALOG_READ
  /api/data-governance/v1/field-details:
    get:
      operationId: get_v1-field-details
      summary: Get Search Fields
      description: Use this API to retrieve a list of all catalog search fields. The response will include details such as the search field names, data types, and supported operators.
      tags:
      - Catalog Search V1
      x-onetrust:
        spec-label: https://developer.onetrust.com/onetrust/openapi/data-use-governance-data-catalog.json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_SearchFieldResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '429':
          description: "Too Many Requests. \nFor more information, see [API Rate Limits](https://developer.onetrust.com/onetrust/reference/rate-limits-overview)."
          headers:
            Retry-After:
              schema:
                description: The number of seconds after which requests will be allowed again.
                format: int32
            ot-period:
              schema:
                description: The unit of time for which the rate limit applies
                enum:
                - HOUR
                - MINUTE
            ot-ratelimit-event-id:
              schema:
                description: The unique identifier for the rate-limiting event.
                format: uuid
            ot-request-made:
              schema:
                description: The number of requests made within the specified period.
                format: int32
            ot-requests-allowed:
              schema:
                description: The number of requests allowed within the specified period.
                format: int32
        '500':
          description: Internal Server Error
      security:
      - DataUseGovernance-DataCatalogMetadataExchange_OAUTH2:
        - DATA_CATALOG_READ
components:
  schemas:
    DataUseGovernance-DataCatalogMetadataExchange_FieldValue:
      type: object
      properties:
        value:
          description: Search field value
          type: object
          example: Employee Details
        nameKey:
          description: Search field name key
          type: string
          example: DataDictionaryParent
        dataType:
          description: Search field data type
          type: string
          example: String
        optionType:
          description: Search field option type
          type: string
          example: users
        enabled:
          description: Search field boolean value
          type: boolean
          example: true
        mappedFieldSchema:
          description: Search field mapped field's schema
          type: string
          example: "\"{\n \"name\": \"ClassificationTerm\",\n \"type\": \"Object\",\n \"fields\": [\n {\n \"type\": \"String\",\n \"name\": \"approvedTerm\",\n \"nameKey\": \"DataDictionaryGovSearchApprovedTerms\"\n },\n {\n \"type\": \"String\",\n \"name\": \"approvedTermId\",\n \"nameKey\": \"DataDictionaryGovSearchApprovedTermIds\"\n },\n {\n \"type\": \"String\",\n \"name\": \"recommendedTerm\",\n \"nameKey\": \"DataDictionaryGovSearchRecommendedTerms\"\n }\n ]\n}\"\n"
    DataUseGovernance-DataCatalogMetadataExchange_OneTrustMetadata:
      type: object
      properties:
        page:
          description: The page number of the results.
          $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_OneTrustPage'
    DataUseGovernance-DataCatalogMetadataExchange_SearchFieldResponse:
      type: object
      properties:
        searchFields:
          type: array
          items:
            $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_SearchFieldV2'
            description: List of search fields with their metadata
    DataUseGovernance-DataCatalogMetadataExchange_SearchFieldV2:
      type: object
      properties:
        searchFieldName:
          description: Name of the search field
          type: string
          example: name
          minLength: 1
        searchFieldDataType:
          description: Data type of the field selected
          type: string
          example: string
        operators:
          type: array
          items:
            type: string
            description: Operators supported by search field
            enum:
            - EQ
            - NOT_EQ
            - GREATER_THAN
            - GREATER_THAN_EQUAL_TO
            - LESS_THAN_EQUAL_TO
            - AFTER_OR_ON
            - BEFORE_OR_ON
            - MORE_THAN
            - CONTAINS
            - BETWEEN
            - WITHIN_THE_LAST
            - DOES_NOT_CONTAIN
            - IS_EMPTY
            - IS_NOT_EMPTY
            - LIST_CONTAINS
            - LIST_DOES_NOT_CONTAIN
            - EQUALS_TO_ANY_OF
            - NOT_EQUALS_TO_ANY_OF
            - EQUALS_TO_ALL_OF
            - NOT_EQUALS_TO_ALL_OF
            - LIST_CONTAINS_ANY_OF
            - LIST_DOES_NOT_CONTAIN_ANY_OF
            example: EQ
    DataUseGovernance-DataCatalogMetadataExchange_Criterion:
      type: object
      properties:
        searchField:
          description: Search field name
          type: string
          example: name
          minLength: 1
        operator:
          description: Search field operator
          type: string
          example: EQ
          enum:
          - EQ
          - NOT_EQ
          - GREATER_THAN
          - GREATER_THAN_EQUAL_TO
          - LESS_THAN_EQUAL_TO
          - AFTER_OR_ON
          - BEFORE_OR_ON
          - MORE_THAN
          - CONTAINS
          - BETWEEN
          - WITHIN_THE_LAST
          - DOES_NOT_CONTAIN
          - IS_EMPTY
          - IS_NOT_EMPTY
          - LIST_CONTAINS
          - LIST_DOES_NOT_CONTAIN
          - EQUALS_TO_ANY_OF
          - NOT_EQUALS_TO_ANY_OF
          - EQUALS_TO_ALL_OF
          - NOT_EQUALS_TO_ALL_OF
          - LIST_CONTAINS_ANY_OF
          - LIST_DOES_NOT_CONTAIN_ANY_OF
        value:
          description: Value for the criterion
          type: string
          example: Table123
        values:
          description: Value range for the criterion
          $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_BetweenValue'
        multiValue:
          type: array
          items:
            type: string
            description: Value for the criterion
            example: EmployeeId
        dateUnitType:
          description: Unit of date value
          type: string
          example: DAYS
          enum:
          - DAYS
          - WEEKS
          - MONTHS
          - YEARS
        searchFieldDataType:
          description: Data type of the field selected
          type: string
          example: string
        searchMode:
          description: Logical operator of the criterion
          type: string
          example: ALL
          enum:
          - ANY
          - ALL
        searchQueryType:
          description: Query type of the criterion
          type: string
          example: SIMPLE
          enum:
          - SIMPLE
          - FULL
        multiValueRanges:
          type: array
          items:
            $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_BetweenValue'
            description: Value range for the criterion
      required:
      - operator
    DataUseGovernance-DataCatalogMetadataExchange_OneTrustSort:
      type: object
      properties:
        direction:
          description: The order (ASC|DESC) by which results are sorted.
          type: string
          enum:
          - ASC
          - DESC
        property:
          description: The criteria by which results are sorted.
          type: string
    DataUseGovernance-DataCatalogMetadataExchange_SearchResponse:
      type: object
      properties:
        facets:
          description: Faceted search results grouped by field
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: integer
              format: int64
        documents:
          description: List of search documents matching the search criteria
          $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_OneTrustResponseListOTSearchDocument'
    DataUseGovernance-DataCatalogMetadataExchange_OneTrustPage:
      type: object
      properties:
        first:
          description: This parameter indicates whether the current page is the first page of the list.
          type: boolean
        last:
          description: This parameter indicates whether the current page is the last page of the list.
          type: boolean
        number:
          description: The page number of the results.
          type: integer
          format: int64
        size:
          description: The number of results per page.
          type: integer
          format: int64
        totalElements:
          description: The total number of results in the list.
          type: integer
          format: int64
        totalPages:
          description: The total number of pages in the list.
          type: integer
          format: int64
        sort:
          description: The sort criteria that dictates the order of the results.
          type: array
          items:
            $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_OneTrustSort'
    DataUseGovernance-DataCatalogMetadataExchange_BetweenValue:
      type: object
      properties:
        from:
          description: Start value for the range
          type: string
          example: '61'
        to:
          description: End value for the range
          type: string
          example: '80'
    DataUseGovernance-DataCatalogMetadataExchange_CriteriaGroup:
      type: object
      properties:
        operator:
          description: Logical operator between criteria
          type: string
          enum:
          - AND
          - OR
        criteria:
          type: array
          items:
            $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_Criterion'
            description: Individual criterion of a criteria
          minItems: 1
      required:
      - operator
    DataUseGovernance-DataCatalogMetadataExchange_SearchRequest:
      type: object
      properties:
        searchText:
          description: Text to search for
          type: string
          example: data privacy
        filterCriteria:
          description: Filter criteria for the search
          $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_FilterCriteria'
        searchFields:
          type: array
          items:
            type: string
            description: Search fields for the filter criteria
            example: description
        facets:
          type: array
          items:
            type: string
            description: Facets to include in the response
            example: documentType
        selectFields:
          type: array
          items:
            type: string
            description: Fields to include in the response
            example: description
        partialSearch:
          description: Whether to perform partial text matching
          type: boolean
          default: 'false'
    DataUseGovernance-DataCatalogMetadataExchange_OneTrustResponseListOTSearchDocument:
      type: object
      properties:
        data:
          description: The parameters that detail entity data.
          type: array
          items:
            $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_OTSearchDocument'
        errors:
          description: This parameter provides error details if 400 Bad Request is returned.
          type: array
          items:
            type: object
        meta:
          description: The configuration parameters of the page.
          $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_OneTrustMetadata'
    DataUseGovernance-DataCatalogMetadataExchange_OTSearchDocument:
      type: object
      properties:
        id:
          description: Unique identifier of the search document
          type: string
          example: 172a829d-0f9f-45ab-b5f5-028d228c6edf
          minLength: 1
        documentType:
          description: Type of the search document
          type: string
          example: metadata
          minLength: 1
        name:
          description: Name of the search document
          type: string
          example: Employee table
          minLength: 1
        properties:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_FieldValue'
          writeOnly: true
        jobId:
          description: Identifier for the job
          type: string
          example: 234a829d-0f9f-45ab-b5f5-028d228abcd
        source:
          description: Source of the search document
          type: string
          example: data-discovery
    DataUseGovernance-DataCatalogMetadataExchange_FilterCriteria:
      type: object
      properties:
        groupOperator:
          description: Logical operator between criteria groups
          type: string
          enum:
          - AND
          - OR
        criteriaGroups:
          type: array
          items:
            $ref: '#/components/schemas/DataUseGovernance-DataCatalogMetadataExchange_CriteriaGroup'
            description: Criteria group of a filter criteria
          minItems: 1
      required:
      - groupOperator
  securitySchemes:
    DataUseGovernance-DataCatalog_OAUTH2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://{hostname}/api/access/v1/oauth/token
          scopes:
            DATA_CATALOG_READ: Access to Data Catalog read operations for external systems
            DATA_CATALOG_WRITE: Access to Data Catalog write operations for external systems
    DataUseGovernance-DataAssetManagement_OAUTH2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://{hostname}/api/access/v1/oauth/token
          scopes:
            DATA_CATALOG_WRITE: Data Catalog Write Scope gives the user access to write operations
            DATA_CATALOG_READ: Data Catalog Read Scope gives the user access to read operations
    DataUseGovernance-DataCatalogMetadataExchange_OAUTH2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://{hostname}/api/access/v1/oauth/token
          scopes:
            DATA_CATALOG_READ: Access to Data Catalog read operations for external systems
x-readme:
  explorer-enabled: false
  proxy-enabled: false
  metrics-enabled: false
x-onetrust:
  spec-label: OpenAPI 3.1.0
